export const commandRegistry = [
  { name: '.register', description: 'Start self-service registration', category: 'registration', permission: 'public', premium: false, enabled: true },
  { name: '.terms', description: 'View Terms of Service', category: 'registration', permission: 'public', premium: false, enabled: true },
  { name: '.profile', description: 'View your profile', category: 'registration', permission: 'public', premium: false, enabled: true },
  { name: '.lang', description: 'View or change language', category: 'registration', permission: 'public', premium: false, enabled: true },
  { name: '.slang', description: 'Configure slang style', category: 'registration', permission: 'public', premium: false, enabled: true },
  { name: '.style', description: 'Configure response style', category: 'registration', permission: 'public', premium: false, enabled: true },
  { name: '.help', description: 'Show help', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.menu', description: 'Show command menu', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.ping', description: 'Check bot health', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.commands', description: 'Show dynamic command statistics', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.searchcommand', description: 'Search the command registry', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.status', description: 'Show service status', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.about', description: 'About THANXIE AI', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.support', description: 'Show support information', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.privacy', description: 'Privacy information', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.version', description: 'Show bot version', category: 'system', permission: 'registered', premium: false, enabled: true },
  { name: '.ai', description: 'Chat with THANXIE AI', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.ask', description: 'Ask a question', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.explain', description: 'Explain a topic', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.summarize', description: 'Summarize text', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.translate', description: 'Translate text', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.rewrite', description: 'Rewrite text', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.grammar', description: 'Improve grammar', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.code', description: 'Generate code', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.debug', description: 'Debug code', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.analyze', description: 'Analyze content', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.brainstorm', description: 'Brainstorm ideas', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.prompt', description: 'Improve a prompt', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.email', description: 'Draft an email', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.caption', description: 'Create a caption', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.story', description: 'Create a story', category: 'ai', permission: 'registered', premium: false, enabled: true },
  { name: '.quote', description: 'Get a quote', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.topic', description: 'Get a topic of the day', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.joke', description: 'Get a joke', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.fact', description: 'Get a fact', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.question', description: 'Get a question of the day', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.motivation', description: 'Get motivation', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.advice', description: 'Get advice', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.poem', description: 'Create a poem', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.affirmation', description: 'Get an affirmation', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.wisdom', description: 'Get wisdom', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.roast', description: 'Generate a playful roast', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.compliment', description: 'Generate a compliment', category: 'content', permission: 'registered', premium: false, enabled: true },
  { name: '.meme', description: 'Create a meme prompt', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.quiz', description: 'Start a quiz', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.trivia', description: 'Trivia question', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.riddle', description: 'Give a riddle', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.8ball', description: 'Magic 8-ball', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.truth', description: 'Truth prompt', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.dare', description: 'Dare prompt', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.ship', description: 'Ship two names', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.rate', description: 'Rate a topic', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.wouldyou', description: 'Would-you-rather', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.neverhave', description: 'Never-have-I-ever', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.emoji', description: 'Emoji challenge', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.guess', description: 'Guessing game', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.dice', description: 'Roll dice', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.coin', description: 'Flip a coin', category: 'fun', permission: 'registered', premium: false, enabled: true },
  { name: '.weather', description: 'Weather lookup', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.time', description: 'Time lookup', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.date', description: 'Date lookup', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.calculator', description: 'Calculator', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.convert', description: 'Unit conversion', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.currency', description: 'Currency conversion', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.define', description: 'Define a word', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.dictionary', description: 'Dictionary lookup', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.qr', description: 'QR workflow', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.uuid', description: 'Generate UUID', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.password', description: 'Generate a secure password', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.json', description: 'Format JSON', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.base64', description: 'Base64 encode/decode', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.regex', description: 'Regex helper', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.timestamp', description: 'Timestamp conversion', category: 'utilities', permission: 'registered', premium: false, enabled: true },
  { name: '.sticker', description: 'Sticker workflow', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.toimage', description: 'Convert supported media to image', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.toaudio', description: 'Convert supported media to audio', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.tovideo', description: 'Convert supported media to video', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.compress', description: 'Compress supported media', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.resize', description: 'Resize supported image', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.crop', description: 'Crop supported image', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.blur', description: 'Blur supported image', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.watermark', description: 'Watermark supported media', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.ocr', description: 'OCR supported image', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.antisticker', description: 'Control sticker protection', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antiimage', description: 'Control image protection', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antivoicenote', description: 'Control voice-note protection', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antimention', description: 'Control mention protection', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antilink', description: 'Control link protection', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antivideo', description: 'Control video protection', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antiaudio', description: 'Control audio protection', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antispam', description: 'Control spam protection', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antiviewonce', description: 'Control view-once protection where supported', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antidelete', description: 'Detect deletion-related events where supported', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.antibad', description: 'Control abusive/bad-word protection', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.badword', description: 'Manage custom moderation words', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.moderation', description: 'Show moderation status', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.mediaquota', description: 'Show your daily media generation quota', category: 'media', permission: 'registered', premium: false, enabled: true },
  { name: '.warn', description: 'Warn a user', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.warnings', description: 'View warnings', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.unwarn', description: 'Remove warning', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.mute', description: 'Restrict a user where supported', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.unmute', description: 'Remove restriction where supported', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.ban', description: 'Block a user where supported', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.unban', description: 'Unblock a user where supported', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.clear', description: 'Delete messages where supported', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.rules', description: 'Show group rules', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.setrules', description: 'Set group rules', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.whitelist', description: 'Manage moderation whitelist', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.blacklist', description: 'Manage moderation blacklist', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.lock', description: 'Lock supported group features', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.unlock', description: 'Unlock supported group features', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.slowmode', description: 'Configure supported slow mode', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.autoapprove', description: 'Auto-approve join requests where officially supported', category: 'moderation', permission: 'admin', premium: false, enabled: true },
  { name: '.community', description: 'Community dashboard', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.members', description: 'Community member summary', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.leaderboard', description: 'Community leaderboard', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.xp', description: 'View XP', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.level', description: 'View level', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.rank', description: 'View rank', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.stats', description: 'View statistics', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.activity', description: 'View activity', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.birthday', description: 'Birthday workflow', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.event', description: 'Community event workflow', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.poll', description: 'Create a poll where supported', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.suggestion', description: 'Community suggestion', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.feedback', description: 'Send feedback', category: 'community', permission: 'registered', premium: false, enabled: true },
  { name: '.pinopino', description: 'Pino Pino dashboard', category: 'pinoPino', permission: 'registered', premium: false, enabled: true },
  { name: '.pinopino-add', description: 'Add Pino Pino', category: 'pinoPino', permission: 'registered', premium: false, enabled: true },
  { name: '.pinopino-remove', description: 'Remove Pino Pino', category: 'pinoPino', permission: 'registered', premium: false, enabled: true },
  { name: '.pinopino-list', description: 'List Pino Pino', category: 'pinoPino', permission: 'registered', premium: false, enabled: true },
  { name: '.pinopino-info', description: 'Pino Pino details', category: 'pinoPino', permission: 'registered', premium: false, enabled: true },
  { name: '.pinopino-suggest', description: 'Suggest frequent contacts', category: 'pinoPino', permission: 'registered', premium: false, enabled: true },
  { name: '.balance', description: 'View balance', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.daily', description: 'Claim daily reward', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.weekly', description: 'Claim weekly reward', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.work', description: 'Work for coins', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.pay', description: 'Pay another user', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.deposit', description: 'Deposit coins', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.withdraw', description: 'Withdraw coins', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.shop', description: 'Open economy shop', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.inventory', description: 'View inventory', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.give', description: 'Give an item', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.economy', description: 'Economy dashboard', category: 'economy', permission: 'registered', premium: false, enabled: true },
  { name: '.giveaway', description: 'Create a giveaway', category: 'giveaways', permission: 'registered', premium: false, enabled: true },
  { name: '.giveaways', description: 'List giveaways', category: 'giveaways', permission: 'registered', premium: false, enabled: true },
  { name: '.giveaway-enter', description: 'Enter giveaway', category: 'giveaways', permission: 'registered', premium: false, enabled: true },
  { name: '.giveaway-end', description: 'End giveaway', category: 'giveaways', permission: 'registered', premium: false, enabled: true },
  { name: '.giveaway-winner', description: 'Select giveaway winner', category: 'giveaways', permission: 'registered', premium: false, enabled: true },
  { name: '.schedule', description: 'Schedule a supported action', category: 'automation', permission: 'registered', premium: false, enabled: true },
  { name: '.schedules', description: 'List schedules', category: 'automation', permission: 'registered', premium: false, enabled: true },
  { name: '.unschedule', description: 'Remove a schedule', category: 'automation', permission: 'registered', premium: false, enabled: true },
  { name: '.reminder', description: 'Create reminder', category: 'automation', permission: 'registered', premium: false, enabled: true },
  { name: '.reminders', description: 'List reminders', category: 'automation', permission: 'registered', premium: false, enabled: true },
  { name: '.autoreply', description: 'Configure supported auto-replies', category: 'automation', permission: 'registered', premium: false, enabled: true },
  { name: '.autowelcome', description: 'Configure supported welcome behavior', category: 'automation', permission: 'registered', premium: false, enabled: true },
  { name: '.autopost', description: 'Configure supported posts', category: 'automation', permission: 'registered', premium: false, enabled: true },
  { name: '.premium', description: 'Premium dashboard', category: 'premium', permission: 'registered', premium: false, enabled: true },
  { name: '.premium-plans', description: 'Show premium plans', category: 'premium', permission: 'registered', premium: false, enabled: true },
  { name: '.premium-status', description: 'Show premium status', category: 'premium', permission: 'registered', premium: false, enabled: true },
  { name: '.premium-buy', description: 'Start premium purchase', category: 'premium', permission: 'registered', premium: false, enabled: true },
  { name: '.premium-features', description: 'Show premium features', category: 'premium', permission: 'registered', premium: true, enabled: true },
  { name: '.premium-help', description: 'Premium help', category: 'premium', permission: 'registered', premium: false, enabled: true },
  { name: '.admin', description: 'Admin dashboard', category: 'admin', permission: 'admin', premium: false, enabled: true },
  { name: '.admins', description: 'List configured admins', category: 'admin', permission: 'admin', premium: false, enabled: true },
  { name: '.adminlog', description: 'View moderation audit log', category: 'admin', permission: 'admin', premium: false, enabled: true },
  { name: '.settings', description: 'Group settings', category: 'admin', permission: 'admin', premium: false, enabled: true },
  { name: '.registration', description: 'Registration settings', category: 'admin', permission: 'admin', premium: false, enabled: true },
  { name: '.registration-status', description: 'Registration status', category: 'admin', permission: 'admin', premium: false, enabled: true },
  { name: '.owner', description: 'Owner dashboard', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.setbotimage', description: 'Change brand image', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.branding', description: 'Show branding', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.brandingstatus', description: 'Branding status', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.resetbranding', description: 'Restore default branding', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.previewbranding', description: 'Preview branding', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.block', description: 'Block user', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.unblock', description: 'Unblock user', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.setbotlanguage', description: 'Set global bot language', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.setbotslang', description: 'Set global bot slang', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.setbottone', description: 'Set global bot tone', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.registration-on', description: 'Enable registration', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.registration-off', description: 'Disable registration', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.registration-group', description: 'Configure registration group', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.broadcast', description: 'Disabled bulk broadcast safeguard', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.maintenance', description: 'Maintenance mode', category: 'owner', permission: 'owner', premium: false, enabled: true },
  { name: '.health', description: 'Detailed health status', category: 'owner', permission: 'owner', premium: false, enabled: true },
];

export function commandsByCategory(category) { return commandRegistry.filter(c => c.category.toLowerCase() === String(category || '').toLowerCase()); }
export function findCommand(name) { return commandRegistry.find(c => c.name === name || c.name === `.${name}`); }
